# Optional Lab: Python, NumPy, and Vectorization

In [1]:
import numpy as np 
import time

## Useful References
- NumPy Documentation: [NumPy.org](https://NumPy.org/doc/stable/)
- A challenging feature topic: [NumPy Broadcasting](https://NumPy.org/doc/stable/user/basics.broadcasting.html)

# Vectors

## Vector Creation

In [2]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4); print(f"np.zeros(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,)); print(f"np.zeros(4,): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4): a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,): a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.81552958 0.88604885 0.47340422 0.48996857], a shape = (4,), a data type = float64


Some data creation routines do not take a shape tuple:

In [3]:
a = np.arange(4); print(f"np.arange(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.arange(3,7); print(f"np.arange(3,7): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.arange(3,8,2); print(f"np.arange(3,8,2): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.linspace(0, 2, 5); print(f"np.linspace(0, 2, 5): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.linspace(0, 2, 5, endpoint=False); print(f"np.linspace(0, 2, 5, endpoint=False): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4); print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4): a = [0 1 2 3], a shape = (4,), a data type = int64
np.arange(3,7): a = [3 4 5 6], a shape = (4,), a data type = int64
np.arange(3,8,2): a = [3 5 7], a shape = (3,), a data type = int64
np.linspace(0, 2, 5): a = [0.  0.5 1.  1.5 2. ], a shape = (5,), a data type = float64
np.linspace(0, 2, 5, endpoint=False): a = [0.  0.4 0.8 1.2 1.6], a shape = (5,), a data type = float64
np.random.rand(4): a = [0.13805704 0.08489318 0.47190569 0.67605298], a shape = (4,), a data type = float64


In [4]:
# values can be specified manually as well
a = np.array([5,4,3,2]);    print(f"np.array([5,4,3,2]):    a = {a},    a shape = {a.shape},    a data type = {a.dtype}")
a = np.array([5.,4,3,2]);   print(f"np.array([5.,4,3,2])    a = {a},    a shape = {a.shape},    a data type = {a.dtype}")

np.array([5,4,3,2]):    a = [5 4 3 2],    a shape = (4,),    a data type = int64
np.array([5.,4,3,2])    a = [5. 4. 3. 2.],    a shape = (4,),    a data type = float64


These have all created a 1D vector `a` and `a.shape` returns the dimensions.

## Operations on Vectors


### Indexing

In [5]:
# Vector indexing operations on 1-D vectors
a = np.arange(10)
print(a)

# access an element
print(f"a[2].shape: {a[2].shape} a[2] = {a[2]}")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

# indexes must be within the range of the vector or they will produce and error
try:
    c = a[15]
except Exception as e:
    print("The error message is: " + str(e))

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2] = 2
a[-1] = 9
The error message is: index 15 is out of bounds for axis 0 with size 10


### Slicing

In [6]:
a = np.arange(10)
print(f"a = {a}")

# access 6 consecutive elements
c = a[2:8:1];   print(f"a[2:8:1] = {c}")

# access 4 elements separated by two
c = a[1:9:2];   print(f"a[1:9:2] = {c}")

# access all elements index 3 and above
c = a[3:];      print(f"a[3:] = {c}")

# access all elements below index 3
c = a[:3];      print(f"a[:3] = {c}")

# access all elements
c = a[:];       print(f"a[:] = {c}")

a = [0 1 2 3 4 5 6 7 8 9]
a[2:8:1] = [2 3 4 5 6 7]
a[1:9:2] = [1 3 5 7]
a[3:] = [3 4 5 6 7 8 9]
a[:3] = [0 1 2]
a[:] = [0 1 2 3 4 5 6 7 8 9]


### Single vector operations

In [7]:
a = np.array([1,2,3,4,5])
print(f"a: {a}")
b = -a
print(f"b = -a: {b}")
b = np.sum(a)
print(f"b = np.sum(a):  {b}")
b = np.mean(a)
print(f"b = np.mean(a): {b}")
b = a**2
print(f"b = a**2:   {b}")

a: [1 2 3 4 5]
b = -a: [-1 -2 -3 -4 -5]
b = np.sum(a):  15
b = np.mean(a): 3.0
b = a**2:   [ 1  4  9 16 25]


### Vector Vector element-wise operations

In [8]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([-1, -2, 3, 4, 5])
print(f"a + b = {a + b}")

# scalar vector operations
c = 2 * a
print(f"c = 2 * a : {c}")

a + b = [ 0  0  6  8 10]
c = 2 * a : [ 2  4  6  8 10]


### Vector Vector dot product

$$ x = \sum_{i=0}^{n-1}{a_i b_i}$$

In [9]:
def dot_product(a, b):
    x = 0
    for i in range(a.shape[0]):
        x += a[i] * b[i]
    return x

In [10]:
# test 1-D
a = np.array([1, 2, 3, 4, 5])
b = np.array([-1, -1, 3, 4, 5])
print(f"dot_product(a, b) = {dot_product(a, b)}")

dot_product(a, b) = 47


In [11]:
# using np.dot(a, b)
a = np.array([1, 2, 3, 4, 5])
b = np.array([-1, -1, 3, 4, 5])
c = np.dot(a, b)
print(f"np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape}")
c = np.dot(b, a)
print(f"np.dot(b, a) = {c}, np.dot(b, a).shape = {c.shape}")

np.dot(a, b) = 47, np.dot(a, b).shape = ()
np.dot(b, a) = 47, np.dot(b, a).shape = ()


### The Need for Speed: vector vs for loop
We utilized the NumPy library because it improves speed memory efficiency. Let's demonstrate:

In [12]:
np.random.seed(1)
a = np.random.rand(10000000) # very large arrays
b = np.random.rand(10000000)

tic = time.time() # capture start time
c = np.dot(a,b)
toc = time.time() # capture end time

print(f"np.dot(a, b) = {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms")

tic = time.time() # capture start time
c = dot_product(a,b)
toc = time.time() # capture end time

print(f"dot_product(a, b) = {c:.4f}")
print(f"For loop version duration: {1000*(toc-tic):.4f} ms")

del(a); del(b)  # remove these big arrays from memeory

np.dot(a, b) = 2501072.5817
Vectorized version duration: 5.4691 ms
dot_product(a, b) = 2501072.5817
For loop version duration: 4014.0607 ms


So, vectorization provides a large speed up in this example. This is because NumPy makes better use of available data parallelism in the underlying hardware. GPU's and modern CPU's implement Single Instruction, Multiple Data (SIMD) pipelines allowing multiple operations to be issued in parallel. This is critical in Machine Learning where the data sets are often very large.

In [13]:
# show common Course 1 example
X = np.array([[1],[2],[3],[4]])
w = np.array([5])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")
print(c)

X[1] has shape (1,)
w has shape (1,)
c has shape ()
10


# Matrices

## Matrix Creation

In [14]:
a = np.zeros((1, 5))
print(f"a shape = {a.shape}, a= {a}")

a = np.zeros((2, 2))
print(f"a shape = {a.shape}, a = {a}")

a = np.random.random_sample((2, 1))
print(f"a shape = {a.shape}, a = {a}")

a shape = (1, 5), a= [[0. 0. 0. 0. 0.]]
a shape = (2, 2), a = [[0. 0.]
 [0. 0.]]
a shape = (2, 1), a = [[0.44236513]
 [0.04997798]]


In [15]:
# Manually specify data
a = np.array([[5], [4], [3]]);  print(f"a shape = {a.shape}, np.array: a = {a}")
a = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print(f"a shape = {a.shape}, np.array: a = {a}")

a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
a shape = (3, 2), np.array: a = [[1 2]
 [3 4]
 [5 6]]


## Operations on Matrices

### Indexing

In [16]:
a = np.arange(6).reshape(-1, 2)     # reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

# access an element
print(f"\na[2,0].shape: {a[2, 0].shape}, a[2,0] = {a[2, 0]}, type(a[2,0]) = {type(a[2,0])} Accessing an element returns a scalar\n")

# access a row
print(f"a[2].shape: {a[2].shape}, a[2] = {a[2]}, type(a[2]) = {type(a[2])}")

# print(a[2][0])
# print(type(a[2][0]))

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape: (), a[2,0] = 4, type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape: (2,), a[2] = [4 5], type(a[2]) = <class 'numpy.ndarray'>


**Reshape**  
The previous example used [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) to shape the array.  
`a = np.arange(6).reshape(-1, 2) `   
This line of code first created a *1-D Vector* of six elements. It then reshaped that vector into a *2-D* array using the reshape command. This could have been written:  
`a = np.arange(6).reshape(3, 2) `  
To arrive at the same 3 row, 2 column array.
The -1 argument tells the routine to compute the number of rows given the size of the array and the number of columns.

### Slicing

In [17]:
# vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

# access 5 consecutive elements
print(f"a[0, 2:7:1] = {a[0, 2:7:1]}, a[0, 2:7:1].shape = {a[0, 2:7:1].shape}, a 1-D array")
print(f"a[0][2:7:1] = {a[0][2:7:1]}, a[0][2:7:1].shape = {a[0][2:7:1].shape}, a 1-D array")

# access 5 consecutive elements in two rows
print(f"\na[:, 2:7:1] =\n{a[:, 2:7:1]}\n a[:, 2:7:1].shape = {a[:, 2:7:1].shape} a 2-D array")

# access all elements
print(f"\na[:,:] = \n{a[:,:]}\na[:,:].shape = {a[:,:].shape}")
# print(a[:][:])

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] = [2 3 4 5 6], a[0, 2:7:1].shape = (5,), a 1-D array
a[0][2:7:1] = [2 3 4 5 6], a[0][2:7:1].shape = (5,), a 1-D array

a[:, 2:7:1] =
[[ 2  3  4  5  6]
 [12 13 14 15 16]]
 a[:, 2:7:1].shape = (2, 5) a 2-D array

a[:,:] = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[:,:].shape = (2, 10)
